name: gh-actions-demo
on: [ push, workflow_dispatch ]
env:
  FILE_NAME: ${{ secrets.FILE_NAME }}
jobs:
  development:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    # continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: カスタムアクション
        uses: ./.github/actions/demo-action

      # - name: Check files before checkout
      #   run: |
      #     echo "Checking files before checkout"
      #     ls -la
      # - name: Check files after checkout
      #   run: |
      #     echo "Checking files after checkout"
      #     ls -la
      # - name: Check content
      #   run: |
      #     echo "Checking content"
      #     cat ${{ env.FILE_NAME }}


    # runs-on: ubuntu-latest
    # steps:
    #   - name: refinement
    #     run: echo "リファインメントできた！"
    #   - name: planning
    #     run: echo "プランニングできた！"
    #   - name: coding
    #     run: echo "コーディングできた！"